title: Maria Quadeer # name of the site
author: Maria Quadeer # name of site's author
email: mariaquadeer@gmail.com # email of site's author
url: https://mariaquadeer.github.io/ # root address of the site
baseurl: # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  I'm a quantum physicist with research experience in quantum state estimation and information theory. 
  I have a strong background in analytical methods, computational modelling, and numerical simulation of noisy quantum systems with C/C++ and Python. 
  I did my Ph.D. at the University of Technology Sydney between 2017-22 under the supervision of Marco Tomamichel and Chris Ferrie.
  

permalink: /:slug.html

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "< Back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
